### ISSUE TITLE
Getting error while request for songs from genres

### ISSUE THREAD

**Issue by Globinnjaliath** [LucasPJS/on_audio_query#12]
Am getting error when I tried to list songs from genre. I used List<SongModel> genreSongs = await OnAudioQuery().queryAudiosFrom(AudiosFromType.GENRE_NAME, genreName); and with GENRE_ID also, both returns error as something like I/Process (26960): Sending signal. PID: 26960 SIG: 9
Lost connection to device

**Comment by LucasPJS** [comment]
Hi, `I/Process (26960): Sending signal. PID: 26960 SIG: 9`` is just a message sent before disconnect from IDE. Everytime your app get a "big crash" this message will appear.

Can you add more information? Android version, on_audio_query version, all error log?

**Comment by Globinnjaliath** [comment]
Android version 10
on_audio_query version 1.1.1
Error log:-
```
E/AndroidRuntime( 9772): FATAL EXCEPTION: main
E/AndroidRuntime( 9772): Process: dev.globin.musicplayer, PID: 9772
E/AndroidRuntime( 9772): android.database.sqlite.SQLiteException: no such column: genre (Sqlite code 1 SQLITE_ERROR): , while compiling: SELECT _data, _display_name, _id, _size, album, album_artist, album_id, artist, artist_id, bookmark, composer, date_added, date_modified, duration, title, track, year, is_alarm, is_music, is_notification, is_podcast, is_ringtone FROM audio WHERE ((is_pending=0) AND (is_trashed=0) AND (volume_name IN ( 'external_primary' ))) AND (genre=?), (OS error - 25:Not a typewriter)
E/AndroidRuntime( 9772): at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:184)
E/AndroidRuntime( 9772): at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
E/AndroidRuntime( 9772): at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
E/AndroidRuntime( 9772): at android.content.ContentResolver.query(ContentResolver.java:955)
E/AndroidRuntime( 9772): at android.content.ContentResolver.query(ContentResolver.java:891)
E/AndroidRuntime( 9772): at android.content.ContentResolver.query(ContentResolver.java:840)
E/AndroidRuntime( 9772): at com.lucasjosino.on_audio_query.query.OnAudiosFromQuery$loadSongsFrom$2.invokeSuspend(OnAudiosFromQuery.kt:57)
E/AndroidRuntime( 9772): at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 9772): at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
E/AndroidRuntime( 9772): at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
E/AndroidRuntime( 9772): at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
E/AndroidRuntime( 9772): at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
E/AndroidRuntime( 9772): at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
I/Process ( 9772): Sending signal. PID: 9772 SIG: 9
Lost connection to device.

```

**Comment by LucasPJS** [comment]
I'll try reproduce this error. 

One more thing, can you add the argument(genreName or genreId) when call `[GENRE_NAME]` or `[GENRE_ID]`? Print them before calling the `[queryAudiosFrom]`.
