### ISSUE TITLE
No album artwork for some files in Android 7

### ISSUE THREAD

**Issue by shaan-mephobic** [LucasPJS/on_audio_query#47]
Few songs that don't have album artwork don't return null(some do) in android 7 when doing 
`await OnAudioQuery().queryArtwork(allAlbums[i].id, ArtworkType.ALBUM);` on the latest releases. This bug is not there in `on_audio_query: 2.2.0`. Also I don't face this bug in android 11 on any version.
This is the error,
```
══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
The following _Exception was thrown resolving an image codec:
Exception: Invalid image data

When the exception was thrown, this was the stack:
#0      _futurize (dart:ui/painting.dart:5394:5)
#1      ImageDescriptor.encoded (dart:ui/painting.dart:5262:12)
#2      instantiateImageCodec (dart:ui/painting.dart:2048:60)
<asynchronous suspension>
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by shaan-mephobic** [comment]
Yes, that seems to be the issue. Returning null when the list is empty fixes it like you said.
